// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module crypto_aead_decrypt_ROUND_5_6 (
        ap_ready,
        s_x0_read,
        s_x1_read,
        s_x2_read,
        s_x3_read,
        s_x4_read,
        C,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);


output   ap_ready;
input  [63:0] s_x0_read;
input  [63:0] s_x1_read;
input  [63:0] s_x2_read;
input  [63:0] s_x3_read;
input  [63:0] s_x4_read;
input  [7:0] C;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;
output  [63:0] ap_return_4;

wire   [63:0] zext_ln47_fu_118_p1;
wire   [63:0] xor_ln47_fu_122_p2;
wire   [63:0] xor_ln54_fu_146_p2;
wire   [63:0] and_ln54_fu_152_p2;
wire   [63:0] xor_ln50_fu_128_p2;
wire   [63:0] xor_ln52_fu_140_p2;
wire   [63:0] xor_ln55_fu_164_p2;
wire   [63:0] xor_ln56_fu_176_p2;
wire   [63:0] and_ln56_fu_182_p2;
wire   [63:0] xor_ln51_fu_134_p2;
wire   [63:0] xor_ln57_fu_194_p2;
wire   [63:0] xor_ln58_fu_206_p2;
wire   [63:0] and_ln58_fu_212_p2;
wire   [63:0] t_fu_158_p2;
wire   [63:0] xor_ln60_fu_224_p2;
wire   [63:0] and_ln55_fu_170_p2;
wire   [63:0] t_2_fu_218_p2;
wire   [63:0] t_1_fu_188_p2;
wire   [63:0] xor_ln62_fu_242_p2;
wire   [63:0] and_ln57_fu_200_p2;
wire   [63:0] t_4_fu_236_p2;
wire   [18:0] trunc_ln41_fu_260_p1;
wire   [44:0] lshr_ln_fu_264_p4;
wire   [27:0] trunc_ln41_1_fu_282_p1;
wire   [35:0] lshr_ln41_1_fu_286_p4;
wire   [63:0] or_ln41_1_fu_296_p3;
wire   [63:0] xor_ln66_fu_304_p2;
wire   [63:0] or_ln_fu_274_p3;
wire   [63:0] t_3_fu_230_p2;
wire   [60:0] trunc_ln41_2_fu_316_p1;
wire   [2:0] lshr_ln41_2_fu_320_p4;
wire   [38:0] trunc_ln41_3_fu_338_p1;
wire   [24:0] lshr_ln41_3_fu_342_p4;
wire   [63:0] or_ln41_3_fu_352_p3;
wire   [63:0] xor_ln67_fu_360_p2;
wire   [63:0] or_ln41_2_fu_330_p3;
wire   [63:0] t_6_fu_254_p2;
wire   [0:0] trunc_ln41_4_fu_372_p1;
wire   [62:0] lshr_ln41_4_fu_376_p4;
wire   [5:0] trunc_ln41_5_fu_394_p1;
wire   [57:0] lshr_ln41_5_fu_398_p4;
wire   [63:0] or_ln41_5_fu_408_p3;
wire   [63:0] xor_ln68_fu_416_p2;
wire   [63:0] or_ln41_4_fu_386_p3;
wire   [63:0] t_5_fu_248_p2;
wire   [9:0] trunc_ln41_6_fu_428_p1;
wire   [53:0] lshr_ln41_6_fu_432_p4;
wire   [16:0] trunc_ln41_7_fu_450_p1;
wire   [46:0] lshr_ln41_7_fu_454_p4;
wire   [63:0] or_ln41_7_fu_464_p3;
wire   [63:0] xor_ln69_fu_472_p2;
wire   [63:0] or_ln41_6_fu_442_p3;
wire   [6:0] trunc_ln41_8_fu_484_p1;
wire   [56:0] lshr_ln41_8_fu_488_p4;
wire   [40:0] trunc_ln41_9_fu_506_p1;
wire   [22:0] lshr_ln41_9_fu_510_p4;
wire   [63:0] or_ln41_9_fu_520_p3;
wire   [63:0] xor_ln70_fu_528_p2;
wire   [63:0] or_ln41_8_fu_498_p3;
wire   [63:0] xor_ln66_1_fu_310_p2;
wire   [63:0] xor_ln67_1_fu_366_p2;
wire   [63:0] xor_ln68_1_fu_422_p2;
wire   [63:0] xor_ln69_1_fu_478_p2;
wire   [63:0] xor_ln70_1_fu_534_p2;

assign and_ln54_fu_152_p2 = (xor_ln54_fu_146_p2 & xor_ln47_fu_122_p2);

assign and_ln55_fu_170_p2 = (xor_ln55_fu_164_p2 & s_x3_read);

assign and_ln56_fu_182_p2 = (xor_ln56_fu_176_p2 & s_x4_read);

assign and_ln57_fu_200_p2 = (xor_ln57_fu_194_p2 & xor_ln50_fu_128_p2);

assign and_ln58_fu_212_p2 = (xor_ln58_fu_206_p2 & s_x1_read);

assign ap_ready = 1'b1;

assign ap_return_0 = xor_ln66_1_fu_310_p2;

assign ap_return_1 = xor_ln67_1_fu_366_p2;

assign ap_return_2 = xor_ln68_1_fu_422_p2;

assign ap_return_3 = xor_ln69_1_fu_478_p2;

assign ap_return_4 = xor_ln70_1_fu_534_p2;

assign lshr_ln41_1_fu_286_p4 = {{t_4_fu_236_p2[63:28]}};

assign lshr_ln41_2_fu_320_p4 = {{t_3_fu_230_p2[63:61]}};

assign lshr_ln41_3_fu_342_p4 = {{t_3_fu_230_p2[63:39]}};

assign lshr_ln41_4_fu_376_p4 = {{t_6_fu_254_p2[63:1]}};

assign lshr_ln41_5_fu_398_p4 = {{t_6_fu_254_p2[63:6]}};

assign lshr_ln41_6_fu_432_p4 = {{t_5_fu_248_p2[63:10]}};

assign lshr_ln41_7_fu_454_p4 = {{t_5_fu_248_p2[63:17]}};

assign lshr_ln41_8_fu_488_p4 = {{t_2_fu_218_p2[63:7]}};

assign lshr_ln41_9_fu_510_p4 = {{t_2_fu_218_p2[63:41]}};

assign lshr_ln_fu_264_p4 = {{t_4_fu_236_p2[63:19]}};

assign or_ln41_1_fu_296_p3 = {{trunc_ln41_1_fu_282_p1}, {lshr_ln41_1_fu_286_p4}};

assign or_ln41_2_fu_330_p3 = {{trunc_ln41_2_fu_316_p1}, {lshr_ln41_2_fu_320_p4}};

assign or_ln41_3_fu_352_p3 = {{trunc_ln41_3_fu_338_p1}, {lshr_ln41_3_fu_342_p4}};

assign or_ln41_4_fu_386_p3 = {{trunc_ln41_4_fu_372_p1}, {lshr_ln41_4_fu_376_p4}};

assign or_ln41_5_fu_408_p3 = {{trunc_ln41_5_fu_394_p1}, {lshr_ln41_5_fu_398_p4}};

assign or_ln41_6_fu_442_p3 = {{trunc_ln41_6_fu_428_p1}, {lshr_ln41_6_fu_432_p4}};

assign or_ln41_7_fu_464_p3 = {{trunc_ln41_7_fu_450_p1}, {lshr_ln41_7_fu_454_p4}};

assign or_ln41_8_fu_498_p3 = {{trunc_ln41_8_fu_484_p1}, {lshr_ln41_8_fu_488_p4}};

assign or_ln41_9_fu_520_p3 = {{trunc_ln41_9_fu_506_p1}, {lshr_ln41_9_fu_510_p4}};

assign or_ln_fu_274_p3 = {{trunc_ln41_fu_260_p1}, {lshr_ln_fu_264_p4}};

assign t_1_fu_188_p2 = (xor_ln52_fu_140_p2 ^ and_ln56_fu_182_p2);

assign t_2_fu_218_p2 = (xor_ln51_fu_134_p2 ^ and_ln58_fu_212_p2);

assign t_3_fu_230_p2 = (xor_ln60_fu_224_p2 ^ and_ln55_fu_170_p2);

assign t_4_fu_236_p2 = (t_fu_158_p2 ^ t_2_fu_218_p2);

assign t_5_fu_248_p2 = (xor_ln62_fu_242_p2 ^ and_ln57_fu_200_p2);

assign t_6_fu_254_p2 = (t_1_fu_188_p2 ^ 64'd18446744073709551615);

assign t_fu_158_p2 = (xor_ln50_fu_128_p2 ^ and_ln54_fu_152_p2);

assign trunc_ln41_1_fu_282_p1 = t_4_fu_236_p2[27:0];

assign trunc_ln41_2_fu_316_p1 = t_3_fu_230_p2[60:0];

assign trunc_ln41_3_fu_338_p1 = t_3_fu_230_p2[38:0];

assign trunc_ln41_4_fu_372_p1 = t_6_fu_254_p2[0:0];

assign trunc_ln41_5_fu_394_p1 = t_6_fu_254_p2[5:0];

assign trunc_ln41_6_fu_428_p1 = t_5_fu_248_p2[9:0];

assign trunc_ln41_7_fu_450_p1 = t_5_fu_248_p2[16:0];

assign trunc_ln41_8_fu_484_p1 = t_2_fu_218_p2[6:0];

assign trunc_ln41_9_fu_506_p1 = t_2_fu_218_p2[40:0];

assign trunc_ln41_fu_260_p1 = t_4_fu_236_p2[18:0];

assign xor_ln47_fu_122_p2 = (zext_ln47_fu_118_p1 ^ s_x2_read);

assign xor_ln50_fu_128_p2 = (s_x4_read ^ s_x0_read);

assign xor_ln51_fu_134_p2 = (s_x4_read ^ s_x3_read);

assign xor_ln52_fu_140_p2 = (xor_ln47_fu_122_p2 ^ s_x1_read);

assign xor_ln54_fu_146_p2 = (s_x1_read ^ 64'd18446744073709551615);

assign xor_ln55_fu_164_p2 = (xor_ln52_fu_140_p2 ^ 64'd18446744073709551615);

assign xor_ln56_fu_176_p2 = (s_x3_read ^ 64'd18446744073709551615);

assign xor_ln57_fu_194_p2 = (xor_ln51_fu_134_p2 ^ 64'd18446744073709551615);

assign xor_ln58_fu_206_p2 = (xor_ln50_fu_128_p2 ^ 64'd18446744073709551615);

assign xor_ln60_fu_224_p2 = (t_fu_158_p2 ^ s_x1_read);

assign xor_ln62_fu_242_p2 = (t_1_fu_188_p2 ^ s_x3_read);

assign xor_ln66_1_fu_310_p2 = (xor_ln66_fu_304_p2 ^ or_ln_fu_274_p3);

assign xor_ln66_fu_304_p2 = (t_4_fu_236_p2 ^ or_ln41_1_fu_296_p3);

assign xor_ln67_1_fu_366_p2 = (xor_ln67_fu_360_p2 ^ or_ln41_2_fu_330_p3);

assign xor_ln67_fu_360_p2 = (t_3_fu_230_p2 ^ or_ln41_3_fu_352_p3);

assign xor_ln68_1_fu_422_p2 = (xor_ln68_fu_416_p2 ^ or_ln41_4_fu_386_p3);

assign xor_ln68_fu_416_p2 = (t_6_fu_254_p2 ^ or_ln41_5_fu_408_p3);

assign xor_ln69_1_fu_478_p2 = (xor_ln69_fu_472_p2 ^ or_ln41_6_fu_442_p3);

assign xor_ln69_fu_472_p2 = (t_5_fu_248_p2 ^ or_ln41_7_fu_464_p3);

assign xor_ln70_1_fu_534_p2 = (xor_ln70_fu_528_p2 ^ or_ln41_8_fu_498_p3);

assign xor_ln70_fu_528_p2 = (t_2_fu_218_p2 ^ or_ln41_9_fu_520_p3);

assign zext_ln47_fu_118_p1 = C;

endmodule //crypto_aead_decrypt_ROUND_5_6
