// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="crypto_aead_encrypt_crypto_aead_encrypt,hls_ip_2021_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160t-fbg484-2,HLS_INPUT_CLOCK=100.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=55.832000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2812,HLS_SYN_LUT=30126,HLS_VERSION=2021_2}" *)

module crypto_aead_encrypt (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        c,
        c_ap_vld,
        clen,
        clen_ap_vld,
        m,
        mlen,
        ad,
        adlen,
        nsec,
        npub,
        k,
        ap_return
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] c;
output   c_ap_vld;
output  [63:0] clen;
output   clen_ap_vld;
input  [7:0] m;
input  [63:0] mlen;
input  [7:0] ad;
input  [63:0] adlen;
input  [7:0] nsec;
input  [7:0] npub;
input  [7:0] k;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] c;
reg c_ap_vld;
reg clen_ap_vld;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_LOADBYTES_1_fu_417_ap_return;
reg   [63:0] K1_reg_1384;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_LOADBYTES_1_fu_425_ap_return;
reg   [63:0] N1_reg_1392;
wire    ap_CS_fsm_state3;
wire   [60:0] empty_fu_887_p1;
wire   [60:0] empty_11_fu_891_p1;
reg   [60:0] empty_11_reg_1408;
wire   [2:0] empty_12_fu_895_p1;
reg   [2:0] empty_12_reg_1413;
wire   [2:0] empty_13_fu_899_p1;
reg   [2:0] empty_13_reg_1418;
wire   [63:0] s_x3_15_fu_938_p2;
wire   [63:0] s_x4_15_fu_944_p2;
wire   [0:0] icmp_ln269_fu_949_p2;
reg   [0:0] icmp_ln269_reg_1456;
wire   [0:0] icmp_ln271_fu_965_p2;
reg   [0:0] icmp_ln271_reg_1460;
wire    ap_CS_fsm_state4;
wire   [31:0] trunc_ln278_fu_1050_p1;
reg   [31:0] trunc_ln278_reg_1539;
wire   [0:0] icmp_ln271_1_fu_1029_p2;
wire   [63:0] s_x4_61_fu_1119_p2;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln287_fu_1134_p2;
reg   [0:0] icmp_ln287_reg_1549;
wire    ap_CS_fsm_state7;
wire   [31:0] trunc_ln296_fu_1207_p1;
reg   [31:0] trunc_ln296_reg_1631;
wire   [0:0] icmp_ln287_1_fu_1197_p2;
wire   [63:0] s_x0_61_fu_1212_p2;
reg   [63:0] s_x0_61_reg_1637;
wire    ap_CS_fsm_state8;
wire   [3:0] add_ln230_fu_1223_p2;
wire    ap_CS_fsm_state9;
wire   [63:0] xor_ln296_fu_1296_p2;
reg   [63:0] xor_ln296_reg_1651;
wire    ap_CS_fsm_state10;
wire   [63:0] s_x3_fu_1350_p2;
reg   [63:0] s_x3_reg_1656;
wire   [63:0] s_x4_75_fu_1355_p2;
reg   [63:0] s_x4_75_reg_1661;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_done;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_idle;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_ready;
wire   [63:0] grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_x_4_out;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_x_4_out_ap_vld;
wire    grp_LOADBYTES_1_fu_417_ap_start;
wire    grp_LOADBYTES_1_fu_417_ap_done;
wire    grp_LOADBYTES_1_fu_417_ap_idle;
wire    grp_LOADBYTES_1_fu_417_ap_ready;
reg   [7:0] grp_LOADBYTES_1_fu_417_p_read;
reg   [31:0] grp_LOADBYTES_1_fu_417_n;
wire    grp_LOADBYTES_1_fu_425_ap_start;
wire    grp_LOADBYTES_1_fu_425_ap_done;
wire    grp_LOADBYTES_1_fu_425_ap_idle;
wire    grp_LOADBYTES_1_fu_425_ap_ready;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_done;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_idle;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_ready;
wire   [63:0] grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_x_out;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_x_out_ap_vld;
wire    grp_ROUND_6_fu_440_ap_ready;
reg   [63:0] grp_ROUND_6_fu_440_s_x0_read;
reg   [63:0] grp_ROUND_6_fu_440_s_x1_read;
reg   [63:0] grp_ROUND_6_fu_440_s_x2_read;
reg   [63:0] grp_ROUND_6_fu_440_s_x3_read;
reg   [63:0] grp_ROUND_6_fu_440_s_x4_read;
reg   [7:0] grp_ROUND_6_fu_440_C;
wire   [63:0] grp_ROUND_6_fu_440_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_440_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_440_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_440_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_440_ap_return_4;
wire    grp_ROUND_6_fu_452_ap_ready;
reg   [7:0] grp_ROUND_6_fu_452_C;
wire   [63:0] grp_ROUND_6_fu_452_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_452_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_452_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_452_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_452_ap_return_4;
wire    grp_ROUND_6_fu_463_ap_ready;
reg   [7:0] grp_ROUND_6_fu_463_C;
wire   [63:0] grp_ROUND_6_fu_463_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_463_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_463_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_463_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_463_ap_return_4;
wire    grp_ROUND_6_fu_474_ap_ready;
reg   [7:0] grp_ROUND_6_fu_474_C;
wire   [63:0] grp_ROUND_6_fu_474_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_474_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_474_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_474_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_474_ap_return_4;
wire    grp_ROUND_6_fu_485_ap_ready;
reg   [7:0] grp_ROUND_6_fu_485_C;
wire   [63:0] grp_ROUND_6_fu_485_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_485_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_485_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_485_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_485_ap_return_4;
wire    grp_ROUND_6_fu_496_ap_ready;
reg   [7:0] grp_ROUND_6_fu_496_C;
wire   [63:0] grp_ROUND_6_fu_496_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_496_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_496_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_496_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_496_ap_return_4;
wire    grp_ROUND_6_fu_507_ap_ready;
wire   [63:0] grp_ROUND_6_fu_507_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_507_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_507_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_507_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_507_ap_return_4;
wire    grp_ROUND_6_fu_518_ap_ready;
wire   [63:0] grp_ROUND_6_fu_518_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_518_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_518_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_518_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_518_ap_return_4;
wire    grp_ROUND_6_fu_529_ap_ready;
wire   [63:0] grp_ROUND_6_fu_529_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_529_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_529_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_529_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_529_ap_return_4;
wire    grp_ROUND_6_fu_540_ap_ready;
wire   [63:0] grp_ROUND_6_fu_540_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_540_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_540_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_540_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_540_ap_return_4;
wire    grp_ROUND_6_fu_551_ap_ready;
wire   [63:0] grp_ROUND_6_fu_551_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_551_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_551_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_551_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_551_ap_return_4;
wire    grp_ROUND_6_fu_562_ap_ready;
wire   [63:0] grp_ROUND_6_fu_562_ap_return_0;
wire   [63:0] grp_ROUND_6_fu_562_ap_return_1;
wire   [63:0] grp_ROUND_6_fu_562_ap_return_2;
wire   [63:0] grp_ROUND_6_fu_562_ap_return_3;
wire   [63:0] grp_ROUND_6_fu_562_ap_return_4;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_done;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_idle;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_ready;
wire   [7:0] grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_c;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_c_ap_vld;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_done;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_idle;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_ready;
wire   [7:0] grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_c;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_c_ap_vld;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_done;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_idle;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_ready;
wire   [7:0] grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_c;
wire    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_c_ap_vld;
wire   [60:0] zext_ln278_fu_1046_p1;
reg   [60:0] ap_phi_mux_adlen_addr_0_lcssa_phi_fu_239_p4;
reg   [60:0] adlen_addr_0_lcssa_reg_236;
reg   [63:0] s_x4_1_reg_246;
reg   [63:0] s_x3_1_reg_255;
reg   [63:0] s_x2_1_reg_264;
reg   [63:0] s_x1_1_reg_273;
reg   [63:0] s_x0_1716_reg_282;
reg   [63:0] ap_phi_mux_s_x4_2723_phi_fu_294_p4;
reg   [63:0] s_x4_2723_reg_291;
reg    ap_block_state6_on_subcall_done;
reg   [63:0] ap_phi_mux_s_x3_2721_phi_fu_303_p4;
reg   [63:0] s_x3_2721_reg_300;
reg   [63:0] ap_phi_mux_s_x2_2720_phi_fu_313_p4;
reg   [63:0] s_x2_2720_reg_310;
reg   [63:0] ap_phi_mux_s_x1_2719_phi_fu_323_p4;
reg   [63:0] s_x1_2719_reg_320;
reg   [63:0] ap_phi_mux_s_x0_2717_phi_fu_333_p4;
reg   [63:0] s_x0_2717_reg_330;
wire   [60:0] zext_ln296_fu_1203_p1;
reg   [60:0] ap_phi_mux_mlen_addr_0_lcssa_phi_fu_343_p4;
reg   [60:0] mlen_addr_0_lcssa_reg_340;
reg   [3:0] i_reg_350;
wire   [0:0] icmp_ln230_fu_1217_p2;
reg   [63:0] s_x4_4_reg_361;
reg   [63:0] s_x3_4722_reg_370;
reg   [63:0] s_x2_4_reg_380;
reg   [63:0] s_x1_4_reg_390;
reg   [63:0] s_x0_4718_reg_400;
reg    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start_reg;
reg    grp_LOADBYTES_1_fu_417_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_LOADBYTES_1_fu_425_ap_start_reg;
reg    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start_reg;
wire   [63:0] s_x0_47_fu_1055_p2;
wire   [63:0] s_x0_54_fu_1112_p2;
wire   [63:0] s_x0_62_fu_1323_p2;
wire   [63:0] s_x1_34_fu_1330_p2;
wire   [63:0] s_x2_59_fu_1336_p2;
reg    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg    grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg   [63:0] adlen_assign_fu_138;
wire   [63:0] add_ln275_fu_1035_p2;
reg   [63:0] s_x0_46_fu_142;
reg   [63:0] s_x1_15_fu_146;
reg   [63:0] s_x2_46_fu_150;
reg   [63:0] s_x3_16_fu_154;
reg   [63:0] s_x4_48_fu_158;
reg   [63:0] mlen_assign_fu_162;
wire   [63:0] add_ln293_fu_1261_p2;
reg   [63:0] s_x0_3_fu_166;
reg   [63:0] s_x1_3_fu_170;
reg   [63:0] s_x2_3_fu_174;
reg   [63:0] s_x3_3_fu_178;
reg   [63:0] s_x4_62_fu_182;
wire   [7:0] trunc_ln230_3_fu_1256_p1;
wire   [60:0] tmp_4_fu_955_p4;
wire   [60:0] tmp_5_fu_1019_p4;
wire   [63:0] shl_ln1_fu_1086_p3;
wire   [63:0] sub_ln279_fu_1094_p2;
wire   [63:0] shl_ln279_fu_1100_p2;
wire   [63:0] xor_ln279_fu_1106_p2;
wire   [60:0] tmp_6_fu_1125_p4;
wire   [60:0] tmp_7_fu_1187_p4;
wire   [2:0] trunc_ln230_fu_1229_p1;
wire   [5:0] shl_ln2_fu_1233_p3;
wire   [5:0] sub_ln230_fu_1241_p2;
wire   [63:0] zext_ln230_fu_1247_p1;
wire   [63:0] lshr_ln230_fu_1251_p2;
wire   [63:0] shl_ln3_fu_1303_p3;
wire   [63:0] sub_ln298_fu_1311_p2;
wire   [63:0] shl_ln298_fu_1317_p2;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start_reg = 1'b0;
#0 grp_LOADBYTES_1_fu_417_ap_start_reg = 1'b0;
#0 grp_LOADBYTES_1_fu_425_ap_start_reg = 1'b0;
#0 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start_reg = 1'b0;
#0 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start_reg = 1'b0;
#0 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start_reg = 1'b0;
#0 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start_reg = 1'b0;
end

crypto_aead_encrypt_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start),
    .ap_done(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_done),
    .ap_idle(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_idle),
    .ap_ready(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_ready),
    .zext_ln224(k),
    .x_4_out(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_x_4_out),
    .x_4_out_ap_vld(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_x_4_out_ap_vld)
);

crypto_aead_encrypt_LOADBYTES_1 grp_LOADBYTES_1_fu_417(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LOADBYTES_1_fu_417_ap_start),
    .ap_done(grp_LOADBYTES_1_fu_417_ap_done),
    .ap_idle(grp_LOADBYTES_1_fu_417_ap_idle),
    .ap_ready(grp_LOADBYTES_1_fu_417_ap_ready),
    .p_read(grp_LOADBYTES_1_fu_417_p_read),
    .n(grp_LOADBYTES_1_fu_417_n),
    .ap_return(grp_LOADBYTES_1_fu_417_ap_return)
);

crypto_aead_encrypt_LOADBYTES_1 grp_LOADBYTES_1_fu_425(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LOADBYTES_1_fu_425_ap_start),
    .ap_done(grp_LOADBYTES_1_fu_425_ap_done),
    .ap_idle(grp_LOADBYTES_1_fu_425_ap_idle),
    .ap_ready(grp_LOADBYTES_1_fu_425_ap_ready),
    .p_read(npub),
    .n(32'd8),
    .ap_return(grp_LOADBYTES_1_fu_425_ap_return)
);

crypto_aead_encrypt_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start),
    .ap_done(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_done),
    .ap_idle(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_idle),
    .ap_ready(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_ready),
    .zext_ln224_1(npub),
    .x_out(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_x_out),
    .x_out_ap_vld(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_x_out_ap_vld)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_440(
    .ap_ready(grp_ROUND_6_fu_440_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_440_s_x0_read),
    .s_x1_read(grp_ROUND_6_fu_440_s_x1_read),
    .s_x2_read(grp_ROUND_6_fu_440_s_x2_read),
    .s_x3_read(grp_ROUND_6_fu_440_s_x3_read),
    .s_x4_read(grp_ROUND_6_fu_440_s_x4_read),
    .C(grp_ROUND_6_fu_440_C),
    .ap_return_0(grp_ROUND_6_fu_440_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_440_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_440_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_440_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_440_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_452(
    .ap_ready(grp_ROUND_6_fu_452_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_440_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_440_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_440_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_440_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_440_ap_return_4),
    .C(grp_ROUND_6_fu_452_C),
    .ap_return_0(grp_ROUND_6_fu_452_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_452_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_452_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_452_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_452_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_463(
    .ap_ready(grp_ROUND_6_fu_463_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_452_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_452_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_452_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_452_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_452_ap_return_4),
    .C(grp_ROUND_6_fu_463_C),
    .ap_return_0(grp_ROUND_6_fu_463_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_463_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_463_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_463_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_463_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_474(
    .ap_ready(grp_ROUND_6_fu_474_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_463_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_463_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_463_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_463_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_463_ap_return_4),
    .C(grp_ROUND_6_fu_474_C),
    .ap_return_0(grp_ROUND_6_fu_474_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_474_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_474_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_474_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_474_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_485(
    .ap_ready(grp_ROUND_6_fu_485_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_474_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_474_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_474_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_474_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_474_ap_return_4),
    .C(grp_ROUND_6_fu_485_C),
    .ap_return_0(grp_ROUND_6_fu_485_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_485_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_485_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_485_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_485_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_496(
    .ap_ready(grp_ROUND_6_fu_496_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_485_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_485_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_485_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_485_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_485_ap_return_4),
    .C(grp_ROUND_6_fu_496_C),
    .ap_return_0(grp_ROUND_6_fu_496_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_496_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_496_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_496_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_496_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_507(
    .ap_ready(grp_ROUND_6_fu_507_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_496_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_496_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_496_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_496_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_496_ap_return_4),
    .C(8'd150),
    .ap_return_0(grp_ROUND_6_fu_507_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_507_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_507_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_507_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_507_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_518(
    .ap_ready(grp_ROUND_6_fu_518_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_507_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_507_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_507_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_507_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_507_ap_return_4),
    .C(8'd135),
    .ap_return_0(grp_ROUND_6_fu_518_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_518_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_518_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_518_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_518_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_529(
    .ap_ready(grp_ROUND_6_fu_529_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_518_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_518_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_518_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_518_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_518_ap_return_4),
    .C(8'd120),
    .ap_return_0(grp_ROUND_6_fu_529_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_529_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_529_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_529_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_529_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_540(
    .ap_ready(grp_ROUND_6_fu_540_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_529_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_529_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_529_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_529_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_529_ap_return_4),
    .C(8'd105),
    .ap_return_0(grp_ROUND_6_fu_540_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_540_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_540_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_540_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_540_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_551(
    .ap_ready(grp_ROUND_6_fu_551_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_540_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_540_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_540_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_540_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_540_ap_return_4),
    .C(8'd90),
    .ap_return_0(grp_ROUND_6_fu_551_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_551_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_551_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_551_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_551_ap_return_4)
);

crypto_aead_encrypt_ROUND_6 grp_ROUND_6_fu_562(
    .ap_ready(grp_ROUND_6_fu_562_ap_ready),
    .s_x0_read(grp_ROUND_6_fu_551_ap_return_0),
    .s_x1_read(grp_ROUND_6_fu_551_ap_return_1),
    .s_x2_read(grp_ROUND_6_fu_551_ap_return_2),
    .s_x3_read(grp_ROUND_6_fu_551_ap_return_3),
    .s_x4_read(grp_ROUND_6_fu_551_ap_return_4),
    .C(8'd75),
    .ap_return_0(grp_ROUND_6_fu_562_ap_return_0),
    .ap_return_1(grp_ROUND_6_fu_562_ap_return_1),
    .ap_return_2(grp_ROUND_6_fu_562_ap_return_2),
    .ap_return_3(grp_ROUND_6_fu_562_ap_return_3),
    .ap_return_4(grp_ROUND_6_fu_562_ap_return_4)
);

crypto_aead_encrypt_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start),
    .ap_done(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_done),
    .ap_idle(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_idle),
    .ap_ready(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_ready),
    .n_assign(trunc_ln296_reg_1631),
    .xor_ln296(xor_ln296_reg_1651),
    .c(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_c),
    .c_ap_vld(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_c_ap_vld)
);

crypto_aead_encrypt_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start),
    .ap_done(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_done),
    .ap_idle(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_idle),
    .ap_ready(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_ready),
    .s_x3(s_x3_reg_1656),
    .c(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_c),
    .c_ap_vld(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_c_ap_vld)
);

crypto_aead_encrypt_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13 grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start),
    .ap_done(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_done),
    .ap_idle(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_idle),
    .ap_ready(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_ready),
    .s_x4_47(s_x4_75_reg_1661),
    .c(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_c),
    .c_ap_vld(grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_c_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LOADBYTES_1_fu_417_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln287_1_fu_1197_p2 == 1'd0) & (icmp_ln287_reg_1549 == 1'd0)) | ((1'b1 == ap_CS_fsm_state7) & ((icmp_ln287_1_fu_1197_p2 == 1'd1) | (icmp_ln287_reg_1549 == 1'd1))) | ((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & ((icmp_ln271_reg_1460 == 1'd1) | (icmp_ln271_1_fu_1029_p2 == 1'd1))))) begin
            grp_LOADBYTES_1_fu_417_ap_start_reg <= 1'b1;
        end else if ((grp_LOADBYTES_1_fu_417_ap_ready == 1'b1)) begin
            grp_LOADBYTES_1_fu_417_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LOADBYTES_1_fu_425_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_LOADBYTES_1_fu_425_ap_start_reg <= 1'b1;
        end else if ((grp_LOADBYTES_1_fu_425_ap_ready == 1'b1)) begin
            grp_LOADBYTES_1_fu_425_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_ready == 1'b1)) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_ready == 1'b1)) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_ready == 1'b1)) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_ready == 1'b1)) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_ready == 1'b1)) begin
            grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd1) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        adlen_addr_0_lcssa_reg_236 <= empty_fu_887_p1;
    end else if (((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd1))) begin
        adlen_addr_0_lcssa_reg_236 <= zext_ln278_fu_1046_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd0) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        adlen_assign_fu_138 <= adlen;
    end else if (((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd0))) begin
        adlen_assign_fu_138 <= add_ln275_fu_1035_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
        i_reg_350 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd0))) begin
        i_reg_350 <= add_ln230_fu_1223_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd1))) begin
        mlen_addr_0_lcssa_reg_340 <= empty_11_reg_1408;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln287_1_fu_1197_p2 == 1'd1) & (icmp_ln287_reg_1549 == 1'd0))) begin
        mlen_addr_0_lcssa_reg_340 <= zext_ln296_fu_1203_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd0))) begin
        mlen_assign_fu_162 <= mlen;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        mlen_assign_fu_162 <= add_ln293_fu_1261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd1) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x0_1716_reg_282 <= grp_ROUND_6_fu_562_ap_return_0;
    end else if (((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd1))) begin
        s_x0_1716_reg_282 <= s_x0_46_fu_142;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln269_fu_949_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x0_2717_reg_330 <= grp_ROUND_6_fu_562_ap_return_0;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        s_x0_2717_reg_330 <= grp_ROUND_6_fu_496_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd0))) begin
        s_x0_3_fu_166 <= ap_phi_mux_s_x0_2717_phi_fu_333_p4;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        s_x0_3_fu_166 <= grp_ROUND_6_fu_496_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd0) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x0_46_fu_142 <= grp_ROUND_6_fu_562_ap_return_0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
        s_x0_46_fu_142 <= grp_ROUND_6_fu_496_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd1))) begin
        s_x0_4718_reg_400 <= ap_phi_mux_s_x0_2717_phi_fu_333_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln287_1_fu_1197_p2 == 1'd1) & (icmp_ln287_reg_1549 == 1'd0))) begin
        s_x0_4718_reg_400 <= s_x0_3_fu_166;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd0) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x1_15_fu_146 <= grp_ROUND_6_fu_562_ap_return_1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
        s_x1_15_fu_146 <= grp_ROUND_6_fu_496_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd1) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x1_1_reg_273 <= grp_ROUND_6_fu_562_ap_return_1;
    end else if (((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd1))) begin
        s_x1_1_reg_273 <= s_x1_15_fu_146;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln269_fu_949_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x1_2719_reg_320 <= grp_ROUND_6_fu_562_ap_return_1;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        s_x1_2719_reg_320 <= grp_ROUND_6_fu_496_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd0))) begin
        s_x1_3_fu_170 <= ap_phi_mux_s_x1_2719_phi_fu_323_p4;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        s_x1_3_fu_170 <= grp_ROUND_6_fu_496_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd1))) begin
        s_x1_4_reg_390 <= ap_phi_mux_s_x1_2719_phi_fu_323_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln287_1_fu_1197_p2 == 1'd1) & (icmp_ln287_reg_1549 == 1'd0))) begin
        s_x1_4_reg_390 <= s_x1_3_fu_170;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd1) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x2_1_reg_264 <= grp_ROUND_6_fu_562_ap_return_2;
    end else if (((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd1))) begin
        s_x2_1_reg_264 <= s_x2_46_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln269_fu_949_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x2_2720_reg_310 <= grp_ROUND_6_fu_562_ap_return_2;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        s_x2_2720_reg_310 <= grp_ROUND_6_fu_496_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd0))) begin
        s_x2_3_fu_174 <= ap_phi_mux_s_x2_2720_phi_fu_313_p4;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        s_x2_3_fu_174 <= grp_ROUND_6_fu_496_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd0) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x2_46_fu_150 <= grp_ROUND_6_fu_562_ap_return_2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
        s_x2_46_fu_150 <= grp_ROUND_6_fu_496_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd1))) begin
        s_x2_4_reg_380 <= ap_phi_mux_s_x2_2720_phi_fu_313_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln287_1_fu_1197_p2 == 1'd1) & (icmp_ln287_reg_1549 == 1'd0))) begin
        s_x2_4_reg_380 <= s_x2_3_fu_174;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd0) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x3_16_fu_154 <= s_x3_15_fu_938_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
        s_x3_16_fu_154 <= grp_ROUND_6_fu_496_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd1) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x3_1_reg_255 <= s_x3_15_fu_938_p2;
    end else if (((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd1))) begin
        s_x3_1_reg_255 <= s_x3_16_fu_154;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln269_fu_949_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x3_2721_reg_300 <= s_x3_15_fu_938_p2;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        s_x3_2721_reg_300 <= grp_ROUND_6_fu_496_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd0))) begin
        s_x3_3_fu_178 <= ap_phi_mux_s_x3_2721_phi_fu_303_p4;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        s_x3_3_fu_178 <= grp_ROUND_6_fu_496_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd1))) begin
        s_x3_4722_reg_370 <= ap_phi_mux_s_x3_2721_phi_fu_303_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln287_1_fu_1197_p2 == 1'd1) & (icmp_ln287_reg_1549 == 1'd0))) begin
        s_x3_4722_reg_370 <= s_x3_3_fu_178;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd1) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x4_1_reg_246 <= s_x4_15_fu_944_p2;
    end else if (((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd1))) begin
        s_x4_1_reg_246 <= s_x4_48_fu_158;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln269_fu_949_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x4_2723_reg_291 <= s_x4_15_fu_944_p2;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        s_x4_2723_reg_291 <= grp_ROUND_6_fu_496_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_965_p2 == 1'd0) & (icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_x4_48_fu_158 <= s_x4_15_fu_944_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
        s_x4_48_fu_158 <= grp_ROUND_6_fu_496_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd1))) begin
        s_x4_4_reg_361 <= s_x4_61_fu_1119_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln287_1_fu_1197_p2 == 1'd1) & (icmp_ln287_reg_1549 == 1'd0))) begin
        s_x4_4_reg_361 <= s_x4_62_fu_182;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln287_fu_1134_p2 == 1'd0))) begin
        s_x4_62_fu_182 <= s_x4_61_fu_1119_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        s_x4_62_fu_182 <= grp_ROUND_6_fu_496_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K1_reg_1384 <= grp_LOADBYTES_1_fu_417_ap_return;
        N1_reg_1392 <= grp_LOADBYTES_1_fu_425_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        empty_11_reg_1408 <= empty_11_fu_891_p1;
        empty_12_reg_1413 <= empty_12_fu_895_p1;
        empty_13_reg_1418 <= empty_13_fu_899_p1;
        icmp_ln269_reg_1456 <= icmp_ln269_fu_949_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln271_reg_1460 <= icmp_ln271_fu_965_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln287_reg_1549 <= icmp_ln287_fu_1134_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        s_x0_61_reg_1637 <= s_x0_61_fu_1212_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        s_x3_reg_1656 <= s_x3_fu_1350_p2;
        s_x4_75_reg_1661 <= s_x4_75_fu_1355_p2;
        xor_ln296_reg_1651 <= xor_ln296_fu_1296_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln271_reg_1460 == 1'd1) | (icmp_ln271_1_fu_1029_p2 == 1'd1)))) begin
        trunc_ln278_reg_1539 <= trunc_ln278_fu_1050_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & ((icmp_ln287_1_fu_1197_p2 == 1'd1) | (icmp_ln287_reg_1549 == 1'd1)))) begin
        trunc_ln296_reg_1631 <= trunc_ln296_fu_1207_p1;
    end
end

always @ (*) begin
    if ((grp_LOADBYTES_1_fu_417_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_LOADBYTES_1_fu_417_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_LOADBYTES_1_fu_417_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_reg_1460 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln271_1_fu_1029_p2 == 1'd1))) begin
        ap_phi_mux_adlen_addr_0_lcssa_phi_fu_239_p4 = zext_ln278_fu_1046_p1;
    end else begin
        ap_phi_mux_adlen_addr_0_lcssa_phi_fu_239_p4 = adlen_addr_0_lcssa_reg_236;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln287_1_fu_1197_p2 == 1'd1) & (icmp_ln287_reg_1549 == 1'd0))) begin
        ap_phi_mux_mlen_addr_0_lcssa_phi_fu_343_p4 = zext_ln296_fu_1203_p1;
    end else begin
        ap_phi_mux_mlen_addr_0_lcssa_phi_fu_343_p4 = mlen_addr_0_lcssa_reg_340;
    end
end

always @ (*) begin
    if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_phi_mux_s_x0_2717_phi_fu_333_p4 = grp_ROUND_6_fu_496_ap_return_0;
    end else begin
        ap_phi_mux_s_x0_2717_phi_fu_333_p4 = s_x0_2717_reg_330;
    end
end

always @ (*) begin
    if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_phi_mux_s_x1_2719_phi_fu_323_p4 = grp_ROUND_6_fu_496_ap_return_1;
    end else begin
        ap_phi_mux_s_x1_2719_phi_fu_323_p4 = s_x1_2719_reg_320;
    end
end

always @ (*) begin
    if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_phi_mux_s_x2_2720_phi_fu_313_p4 = grp_ROUND_6_fu_496_ap_return_2;
    end else begin
        ap_phi_mux_s_x2_2720_phi_fu_313_p4 = s_x2_2720_reg_310;
    end
end

always @ (*) begin
    if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_phi_mux_s_x3_2721_phi_fu_303_p4 = grp_ROUND_6_fu_496_ap_return_3;
    end else begin
        ap_phi_mux_s_x3_2721_phi_fu_303_p4 = s_x3_2721_reg_300;
    end
end

always @ (*) begin
    if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_phi_mux_s_x4_2723_phi_fu_294_p4 = grp_ROUND_6_fu_496_ap_return_4;
    end else begin
        ap_phi_mux_s_x4_2723_phi_fu_294_p4 = s_x4_2723_reg_291;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd0))) begin
        c = trunc_ln230_3_fu_1256_p1;
    end else if (((1'b1 == ap_CS_fsm_state15) & (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_c_ap_vld == 1'b1))) begin
        c = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_c;
    end else if (((1'b1 == ap_CS_fsm_state13) & (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_c_ap_vld == 1'b1))) begin
        c = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_c;
    end else if (((1'b1 == ap_CS_fsm_state11) & (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_c_ap_vld == 1'b1))) begin
        c = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_c;
    end else begin
        c = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd0))) begin
        c_ap_vld = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        c_ap_vld = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_c_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        c_ap_vld = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_c_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        c_ap_vld = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_c_ap_vld;
    end else begin
        c_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        clen_ap_vld = 1'b1;
    end else begin
        clen_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_LOADBYTES_1_fu_417_n = trunc_ln296_reg_1631;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_LOADBYTES_1_fu_417_n = trunc_ln278_reg_1539;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_LOADBYTES_1_fu_417_n = 32'd8;
    end else begin
        grp_LOADBYTES_1_fu_417_n = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_LOADBYTES_1_fu_417_p_read = m;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_LOADBYTES_1_fu_417_p_read = ad;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_LOADBYTES_1_fu_417_p_read = k;
    end else begin
        grp_LOADBYTES_1_fu_417_p_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1)))) begin
        grp_ROUND_6_fu_440_C = 8'd150;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_ROUND_6_fu_440_C = 8'd240;
    end else begin
        grp_ROUND_6_fu_440_C = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_ROUND_6_fu_440_s_x0_read = s_x0_62_fu_1323_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        grp_ROUND_6_fu_440_s_x0_read = s_x0_61_reg_1637;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_ROUND_6_fu_440_s_x0_read = s_x0_54_fu_1112_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_6_fu_440_s_x0_read = s_x0_47_fu_1055_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_6_fu_440_s_x0_read = 64'd9241399655273594880;
    end else begin
        grp_ROUND_6_fu_440_s_x0_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_ROUND_6_fu_440_s_x1_read = s_x1_34_fu_1330_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        grp_ROUND_6_fu_440_s_x1_read = s_x1_3_fu_170;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_ROUND_6_fu_440_s_x1_read = s_x1_1_reg_273;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_6_fu_440_s_x1_read = s_x1_15_fu_146;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_6_fu_440_s_x1_read = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_x_4_out;
    end else begin
        grp_ROUND_6_fu_440_s_x1_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_ROUND_6_fu_440_s_x2_read = s_x2_59_fu_1336_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        grp_ROUND_6_fu_440_s_x2_read = s_x2_3_fu_174;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_ROUND_6_fu_440_s_x2_read = s_x2_1_reg_264;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_6_fu_440_s_x2_read = s_x2_46_fu_150;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_6_fu_440_s_x2_read = K1_reg_1384;
    end else begin
        grp_ROUND_6_fu_440_s_x2_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_ROUND_6_fu_440_s_x3_read = s_x3_4722_reg_370;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        grp_ROUND_6_fu_440_s_x3_read = s_x3_3_fu_178;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_ROUND_6_fu_440_s_x3_read = s_x3_1_reg_255;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_6_fu_440_s_x3_read = s_x3_16_fu_154;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_6_fu_440_s_x3_read = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_x_out;
    end else begin
        grp_ROUND_6_fu_440_s_x3_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_ROUND_6_fu_440_s_x4_read = s_x4_4_reg_361;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
        grp_ROUND_6_fu_440_s_x4_read = s_x4_62_fu_182;
    end else if (((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_ROUND_6_fu_440_s_x4_read = s_x4_1_reg_246;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_6_fu_440_s_x4_read = s_x4_48_fu_158;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_6_fu_440_s_x4_read = N1_reg_1392;
    end else begin
        grp_ROUND_6_fu_440_s_x4_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1)))) begin
        grp_ROUND_6_fu_452_C = 8'd135;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_ROUND_6_fu_452_C = 8'd225;
    end else begin
        grp_ROUND_6_fu_452_C = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1)))) begin
        grp_ROUND_6_fu_463_C = 8'd120;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_ROUND_6_fu_463_C = 8'd210;
    end else begin
        grp_ROUND_6_fu_463_C = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1)))) begin
        grp_ROUND_6_fu_474_C = 8'd105;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_ROUND_6_fu_474_C = 8'd195;
    end else begin
        grp_ROUND_6_fu_474_C = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1)))) begin
        grp_ROUND_6_fu_485_C = 8'd90;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_ROUND_6_fu_485_C = 8'd180;
    end else begin
        grp_ROUND_6_fu_485_C = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln269_reg_1456 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1)))) begin
        grp_ROUND_6_fu_496_C = 8'd75;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_ROUND_6_fu_496_C = 8'd165;
    end else begin
        grp_ROUND_6_fu_496_C = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln269_fu_949_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln271_reg_1460 == 1'd1) | (icmp_ln271_1_fu_1029_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & ((icmp_ln287_1_fu_1197_p2 == 1'd1) | (icmp_ln287_reg_1549 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln230_fu_1217_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln230_fu_1223_p2 = (i_reg_350 + 4'd1);

assign add_ln275_fu_1035_p2 = ($signed(adlen_assign_fu_138) + $signed(64'd18446744073709551608));

assign add_ln293_fu_1261_p2 = ($signed(mlen_assign_fu_162) + $signed(64'd18446744073709551608));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_done == 1'b0) | (grp_LOADBYTES_1_fu_425_ap_done == 1'b0) | (grp_LOADBYTES_1_fu_417_ap_done == 1'b0) | (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state6_on_subcall_done = ((icmp_ln269_reg_1456 == 1'd0) & (grp_LOADBYTES_1_fu_417_ap_done == 1'b0));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign ap_return = 32'd0;

assign clen = (mlen + 64'd16);

assign empty_11_fu_891_p1 = mlen[60:0];

assign empty_12_fu_895_p1 = adlen[2:0];

assign empty_13_fu_899_p1 = mlen[2:0];

assign empty_fu_887_p1 = adlen[60:0];

assign grp_LOADBYTES_1_fu_417_ap_start = grp_LOADBYTES_1_fu_417_ap_start_reg;

assign grp_LOADBYTES_1_fu_425_ap_start = grp_LOADBYTES_1_fu_425_ap_start_reg;

assign grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_11_fu_433_ap_start_reg;

assign grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_ap_start_reg;

assign grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_12_fu_593_ap_start_reg;

assign grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_13_fu_600_ap_start_reg;

assign grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start = grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_230_1_fu_585_ap_start_reg;

assign icmp_ln230_fu_1217_p2 = ((i_reg_350 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln269_fu_949_p2 = ((adlen == 64'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_1_fu_1029_p2 = ((tmp_5_fu_1019_p4 == 61'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_965_p2 = ((tmp_4_fu_955_p4 == 61'd0) ? 1'b1 : 1'b0);

assign icmp_ln287_1_fu_1197_p2 = ((tmp_7_fu_1187_p4 == 61'd0) ? 1'b1 : 1'b0);

assign icmp_ln287_fu_1134_p2 = ((tmp_6_fu_1125_p4 == 61'd0) ? 1'b1 : 1'b0);

assign lshr_ln230_fu_1251_p2 = s_x0_61_reg_1637 >> zext_ln230_fu_1247_p1;

assign s_x0_47_fu_1055_p2 = (s_x0_46_fu_142 ^ grp_LOADBYTES_1_fu_417_ap_return);

assign s_x0_54_fu_1112_p2 = (xor_ln279_fu_1106_p2 ^ s_x0_1716_reg_282);

assign s_x0_61_fu_1212_p2 = (s_x0_3_fu_166 ^ grp_LOADBYTES_1_fu_417_ap_return);

assign s_x0_62_fu_1323_p2 = (xor_ln296_fu_1296_p2 ^ shl_ln298_fu_1317_p2);

assign s_x1_34_fu_1330_p2 = (s_x1_4_reg_390 ^ grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_x_4_out);

assign s_x2_59_fu_1336_p2 = (s_x2_4_reg_380 ^ K1_reg_1384);

assign s_x3_15_fu_938_p2 = (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_x_4_out ^ grp_ROUND_6_fu_562_ap_return_3);

assign s_x3_fu_1350_p2 = (grp_crypto_aead_encrypt_Pipeline_VITIS_LOOP_224_1_fu_410_x_4_out ^ grp_ROUND_6_fu_562_ap_return_3);

assign s_x4_15_fu_944_p2 = (grp_ROUND_6_fu_562_ap_return_4 ^ K1_reg_1384);

assign s_x4_61_fu_1119_p2 = (ap_phi_mux_s_x4_2723_phi_fu_294_p4 ^ 64'd1);

assign s_x4_75_fu_1355_p2 = (grp_ROUND_6_fu_562_ap_return_4 ^ K1_reg_1384);

assign shl_ln1_fu_1086_p3 = {{adlen_addr_0_lcssa_reg_236}, {3'd0}};

assign shl_ln279_fu_1100_p2 = 64'd128 << sub_ln279_fu_1094_p2;

assign shl_ln298_fu_1317_p2 = 64'd128 << sub_ln298_fu_1311_p2;

assign shl_ln2_fu_1233_p3 = {{trunc_ln230_fu_1229_p1}, {3'd0}};

assign shl_ln3_fu_1303_p3 = {{mlen_addr_0_lcssa_reg_340}, {3'd0}};

assign sub_ln230_fu_1241_p2 = ($signed(6'd56) - $signed(shl_ln2_fu_1233_p3));

assign sub_ln279_fu_1094_p2 = (64'd56 - shl_ln1_fu_1086_p3);

assign sub_ln298_fu_1311_p2 = (64'd56 - shl_ln3_fu_1303_p3);

assign tmp_4_fu_955_p4 = {{adlen[63:3]}};

assign tmp_5_fu_1019_p4 = {{adlen_assign_fu_138[63:3]}};

assign tmp_6_fu_1125_p4 = {{mlen[63:3]}};

assign tmp_7_fu_1187_p4 = {{mlen_assign_fu_162[63:3]}};

assign trunc_ln230_3_fu_1256_p1 = lshr_ln230_fu_1251_p2[7:0];

assign trunc_ln230_fu_1229_p1 = i_reg_350[2:0];

assign trunc_ln278_fu_1050_p1 = ap_phi_mux_adlen_addr_0_lcssa_phi_fu_239_p4[31:0];

assign trunc_ln296_fu_1207_p1 = ap_phi_mux_mlen_addr_0_lcssa_phi_fu_343_p4[31:0];

assign xor_ln279_fu_1106_p2 = (shl_ln279_fu_1100_p2 ^ grp_LOADBYTES_1_fu_417_ap_return);

assign xor_ln296_fu_1296_p2 = (s_x0_4718_reg_400 ^ grp_LOADBYTES_1_fu_417_ap_return);

assign zext_ln230_fu_1247_p1 = sub_ln230_fu_1241_p2;

assign zext_ln278_fu_1046_p1 = empty_12_reg_1413;

assign zext_ln296_fu_1203_p1 = empty_13_reg_1418;

endmodule //crypto_aead_encrypt
