// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="crypto_aead_decrypt_crypto_aead_decrypt,hls_ip_2021_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160t-fbg484-2,HLS_INPUT_CLOCK=100.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=59.542000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3268,HLS_SYN_LUT=30964,HLS_VERSION=2021_2}" *)

module crypto_aead_decrypt (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m,
        m_ap_vld,
        mlen,
        mlen_ap_vld,
        nsec,
        c,
        clen,
        ad,
        adlen,
        npub,
        k,
        ap_return
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] m;
output   m_ap_vld;
output  [63:0] mlen;
output   mlen_ap_vld;
input  [7:0] nsec;
input  [7:0] c;
input  [63:0] clen;
input  [7:0] ad;
input  [63:0] adlen;
input  [7:0] npub;
input  [7:0] k;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] m;
reg m_ap_vld;
reg mlen_ap_vld;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_LOADBYTES_1_1_fu_475_ap_return;
reg   [63:0] reg_958;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state10;
wire   [60:0] empty_fu_963_p1;
reg   [60:0] empty_reg_1545;
wire   [2:0] empty_16_fu_967_p1;
reg   [2:0] empty_16_reg_1550;
wire   [2:0] empty_17_fu_971_p1;
reg   [2:0] empty_17_reg_1555;
wire   [0:0] icmp_ln248_fu_985_p2;
reg   [0:0] icmp_ln248_reg_1560;
reg   [63:0] K1_reg_1576;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_LOADBYTES_1_1_fu_483_ap_return;
reg   [63:0] N1_reg_1584;
wire   [63:0] add_ln251_fu_994_p2;
reg   [63:0] add_ln251_reg_1589;
wire    ap_CS_fsm_state3;
wire   [60:0] add_ln251_1_fu_1000_p2;
reg   [60:0] add_ln251_1_reg_1595;
wire   [63:0] s_x3_15_fu_1034_p2;
wire   [63:0] s_x4_15_fu_1040_p2;
wire   [0:0] icmp_ln271_fu_1045_p2;
reg   [0:0] icmp_ln271_reg_1633;
wire   [0:0] icmp_ln273_fu_1059_p2;
reg   [0:0] icmp_ln273_reg_1637;
wire    ap_CS_fsm_state4;
wire   [31:0] trunc_ln280_fu_1143_p1;
reg   [31:0] trunc_ln280_reg_1716;
wire   [0:0] icmp_ln273_1_fu_1122_p2;
wire   [63:0] s_x4_61_fu_1212_p2;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln290_fu_1227_p2;
reg   [0:0] icmp_ln290_reg_1726;
wire    ap_CS_fsm_state7;
wire   [31:0] trunc_ln300_fu_1300_p1;
reg   [31:0] trunc_ln300_reg_1809;
wire   [0:0] icmp_ln290_1_fu_1290_p2;
wire   [0:0] icmp_ln230_1_fu_1305_p2;
reg   [0:0] icmp_ln230_1_reg_1814;
wire   [63:0] xor_ln292_fu_1311_p2;
reg   [63:0] xor_ln292_reg_1818;
wire   [3:0] add_ln230_fu_1322_p2;
wire    ap_CS_fsm_state9;
wire   [63:0] xor_ln301_fu_1395_p2;
reg   [63:0] xor_ln301_reg_1831;
wire   [30:0] trunc_ln230_fu_1402_p1;
reg   [30:0] trunc_ln230_reg_1836;
wire   [63:0] s_x3_fu_1465_p2;
reg   [63:0] s_x3_reg_1842;
wire    ap_CS_fsm_state12;
wire   [63:0] s_x4_75_fu_1471_p2;
reg   [63:0] s_x4_75_reg_1847;
reg   [3:0] t_address0;
reg    t_ce0;
reg    t_we0;
reg   [7:0] t_d0;
wire   [7:0] t_q0;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_done;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_idle;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_ready;
wire   [63:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_x_4_out;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_x_4_out_ap_vld;
wire    grp_LOADBYTES_1_1_fu_475_ap_start;
wire    grp_LOADBYTES_1_1_fu_475_ap_done;
wire    grp_LOADBYTES_1_1_fu_475_ap_idle;
wire    grp_LOADBYTES_1_1_fu_475_ap_ready;
reg   [7:0] grp_LOADBYTES_1_1_fu_475_p_read;
reg   [31:0] grp_LOADBYTES_1_1_fu_475_n;
wire    grp_LOADBYTES_1_1_fu_483_ap_start;
wire    grp_LOADBYTES_1_1_fu_483_ap_done;
wire    grp_LOADBYTES_1_1_fu_483_ap_idle;
wire    grp_LOADBYTES_1_1_fu_483_ap_ready;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_done;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_idle;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_ready;
wire   [63:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_x_out;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_x_out_ap_vld;
wire    grp_ROUND_5_6_fu_498_ap_ready;
reg   [63:0] grp_ROUND_5_6_fu_498_s_x0_read;
reg   [63:0] grp_ROUND_5_6_fu_498_s_x1_read;
reg   [63:0] grp_ROUND_5_6_fu_498_s_x2_read;
reg   [63:0] grp_ROUND_5_6_fu_498_s_x3_read;
reg   [63:0] grp_ROUND_5_6_fu_498_s_x4_read;
reg   [7:0] grp_ROUND_5_6_fu_498_C;
wire   [63:0] grp_ROUND_5_6_fu_498_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_498_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_498_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_498_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_498_ap_return_4;
wire    grp_ROUND_5_6_fu_510_ap_ready;
reg   [7:0] grp_ROUND_5_6_fu_510_C;
wire   [63:0] grp_ROUND_5_6_fu_510_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_510_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_510_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_510_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_510_ap_return_4;
wire    grp_ROUND_5_6_fu_521_ap_ready;
reg   [7:0] grp_ROUND_5_6_fu_521_C;
wire   [63:0] grp_ROUND_5_6_fu_521_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_521_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_521_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_521_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_521_ap_return_4;
wire    grp_ROUND_5_6_fu_532_ap_ready;
reg   [7:0] grp_ROUND_5_6_fu_532_C;
wire   [63:0] grp_ROUND_5_6_fu_532_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_532_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_532_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_532_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_532_ap_return_4;
wire    grp_ROUND_5_6_fu_543_ap_ready;
reg   [7:0] grp_ROUND_5_6_fu_543_C;
wire   [63:0] grp_ROUND_5_6_fu_543_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_543_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_543_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_543_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_543_ap_return_4;
wire    grp_ROUND_5_6_fu_554_ap_ready;
reg   [7:0] grp_ROUND_5_6_fu_554_C;
wire   [63:0] grp_ROUND_5_6_fu_554_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_554_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_554_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_554_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_554_ap_return_4;
wire    grp_ROUND_5_6_fu_565_ap_ready;
wire   [63:0] grp_ROUND_5_6_fu_565_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_565_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_565_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_565_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_565_ap_return_4;
wire    grp_ROUND_5_6_fu_576_ap_ready;
wire   [63:0] grp_ROUND_5_6_fu_576_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_576_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_576_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_576_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_576_ap_return_4;
wire    grp_ROUND_5_6_fu_587_ap_ready;
wire   [63:0] grp_ROUND_5_6_fu_587_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_587_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_587_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_587_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_587_ap_return_4;
wire    grp_ROUND_5_6_fu_598_ap_ready;
wire   [63:0] grp_ROUND_5_6_fu_598_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_598_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_598_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_598_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_598_ap_return_4;
wire    grp_ROUND_5_6_fu_609_ap_ready;
wire   [63:0] grp_ROUND_5_6_fu_609_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_609_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_609_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_609_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_609_ap_return_4;
wire    grp_ROUND_5_6_fu_620_ap_ready;
wire   [63:0] grp_ROUND_5_6_fu_620_ap_return_0;
wire   [63:0] grp_ROUND_5_6_fu_620_ap_return_1;
wire   [63:0] grp_ROUND_5_6_fu_620_ap_return_2;
wire   [63:0] grp_ROUND_5_6_fu_620_ap_return_3;
wire   [63:0] grp_ROUND_5_6_fu_620_ap_return_4;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_done;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_idle;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_ready;
wire   [7:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_m;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_m_ap_vld;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_done;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_idle;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_ready;
wire   [63:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_x_assign_3_out;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_x_assign_3_out_ap_vld;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_done;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_idle;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_ready;
wire   [3:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_address0;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_ce0;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_we0;
wire   [7:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_d0;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_done;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_idle;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_ready;
wire   [3:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_address0;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_ce0;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_we0;
wire   [7:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_d0;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_done;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_idle;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_ready;
wire   [3:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_t_address0;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_t_ce0;
wire   [8:0] grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_result_1_out;
wire    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_result_1_out_ap_vld;
wire   [60:0] zext_ln280_fu_1139_p1;
reg   [60:0] ap_phi_mux_adlen_addr_0_lcssa_phi_fu_271_p4;
reg   [60:0] adlen_addr_0_lcssa_reg_268;
reg   [63:0] s_x4_1_reg_278;
reg   [63:0] s_x3_1_reg_287;
reg   [63:0] s_x2_1_reg_296;
reg   [63:0] s_x1_1_reg_305;
reg   [63:0] s_x0_1716_reg_314;
reg   [63:0] ap_phi_mux_s_x4_2723_phi_fu_326_p4;
reg   [63:0] s_x4_2723_reg_323;
reg    ap_block_state6_on_subcall_done;
reg   [63:0] ap_phi_mux_s_x3_2721_phi_fu_335_p4;
reg   [63:0] s_x3_2721_reg_332;
reg   [63:0] ap_phi_mux_s_x2_2720_phi_fu_345_p4;
reg   [63:0] s_x2_2720_reg_342;
reg   [63:0] ap_phi_mux_s_x1_2719_phi_fu_355_p4;
reg   [63:0] s_x1_2719_reg_352;
reg   [63:0] ap_phi_mux_s_x0_2717_phi_fu_365_p4;
reg   [63:0] s_x0_2717_reg_362;
wire   [60:0] zext_ln300_fu_1296_p1;
reg   [60:0] ap_phi_mux_clen_addr_0_lcssa_phi_fu_375_p4;
reg   [60:0] clen_addr_0_lcssa_reg_372;
reg   [3:0] i_reg_382;
wire   [0:0] icmp_ln230_fu_1316_p2;
reg   [63:0] s_x4_4_reg_393;
reg   [63:0] s_x3_4722_reg_403;
reg   [63:0] s_x2_4_reg_414;
reg   [63:0] s_x1_4_reg_425;
reg   [63:0] x_assign_1_reg_436;
reg   [63:0] ap_phi_mux_x_addr_0_lcssa_i_phi_fu_450_p4;
reg   [63:0] x_addr_0_lcssa_i_reg_447;
wire   [0:0] result_fu_1493_p2;
reg   [0:0] ap_phi_mux_retval_0_phi_fu_461_p4;
reg   [0:0] retval_0_reg_457;
wire    ap_CS_fsm_state18;
reg    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start_reg;
reg    grp_LOADBYTES_1_1_fu_475_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_LOADBYTES_1_1_fu_483_ap_start_reg;
reg    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start_reg;
wire   [63:0] s_x0_46_fu_1148_p2;
wire   [63:0] s_x0_53_fu_1205_p2;
wire   [63:0] s_x0_60_fu_1438_p2;
wire   [63:0] s_x1_34_fu_1445_p2;
wire   [63:0] s_x2_59_fu_1451_p2;
reg    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start_reg;
reg    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start_reg;
wire    ap_CS_fsm_state13;
reg    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg   [8:0] result_1_loc_fu_150;
reg   [63:0] adlen_assign_fu_170;
wire   [63:0] add_ln277_fu_1128_p2;
reg   [63:0] s_x0_27_fu_174;
reg   [63:0] s_x1_15_fu_178;
reg   [63:0] s_x2_46_fu_182;
reg   [63:0] s_x3_16_fu_186;
reg   [63:0] s_x4_48_fu_190;
reg   [63:0] clen_assign_1_fu_194;
wire   [63:0] add_ln297_fu_1360_p2;
reg   [63:0] s_x0_3_fu_198;
reg   [63:0] s_x1_3_fu_202;
reg   [63:0] s_x2_3_fu_206;
reg   [63:0] s_x3_3_fu_210;
reg   [63:0] s_x4_62_fu_214;
wire   [7:0] trunc_ln230_5_fu_1355_p1;
wire   [59:0] tmp_2_fu_975_p4;
wire   [60:0] trunc_ln251_fu_991_p1;
wire   [60:0] tmp_3_fu_1050_p4;
wire   [60:0] tmp_4_fu_1112_p4;
wire   [63:0] shl_ln1_fu_1179_p3;
wire   [63:0] sub_ln281_fu_1187_p2;
wire   [63:0] shl_ln281_fu_1193_p2;
wire   [63:0] xor_ln281_fu_1199_p2;
wire   [60:0] tmp_5_fu_1218_p4;
wire   [60:0] tmp_6_fu_1280_p4;
wire   [2:0] trunc_ln230_4_fu_1328_p1;
wire   [5:0] shl_ln2_fu_1332_p3;
wire   [5:0] sub_ln230_fu_1340_p2;
wire   [63:0] zext_ln230_fu_1346_p1;
wire   [63:0] lshr_ln230_fu_1350_p2;
wire   [63:0] shl_ln4_fu_1418_p3;
wire   [63:0] sub_ln304_fu_1426_p2;
wire   [63:0] or_ln303_fu_1412_p2;
wire   [63:0] shl_ln304_fu_1432_p2;
wire   [8:0] add_ln324_fu_1479_p2;
wire   [0:0] tmp_7_fu_1485_p3;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_block_state11_on_subcall_done;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start_reg = 1'b0;
#0 grp_LOADBYTES_1_1_fu_475_ap_start_reg = 1'b0;
#0 grp_LOADBYTES_1_1_fu_483_ap_start_reg = 1'b0;
#0 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start_reg = 1'b0;
#0 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start_reg = 1'b0;
#0 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start_reg = 1'b0;
#0 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start_reg = 1'b0;
#0 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start_reg = 1'b0;
#0 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start_reg = 1'b0;
end

crypto_aead_decrypt_t_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
t_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(t_address0),
    .ce0(t_ce0),
    .we0(t_we0),
    .d0(t_d0),
    .q0(t_q0)
);

crypto_aead_decrypt_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start),
    .ap_done(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_done),
    .ap_idle(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_idle),
    .ap_ready(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_ready),
    .zext_ln224(k),
    .x_4_out(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_x_4_out),
    .x_4_out_ap_vld(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_x_4_out_ap_vld)
);

crypto_aead_decrypt_LOADBYTES_1_1 grp_LOADBYTES_1_1_fu_475(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LOADBYTES_1_1_fu_475_ap_start),
    .ap_done(grp_LOADBYTES_1_1_fu_475_ap_done),
    .ap_idle(grp_LOADBYTES_1_1_fu_475_ap_idle),
    .ap_ready(grp_LOADBYTES_1_1_fu_475_ap_ready),
    .p_read(grp_LOADBYTES_1_1_fu_475_p_read),
    .n(grp_LOADBYTES_1_1_fu_475_n),
    .ap_return(grp_LOADBYTES_1_1_fu_475_ap_return)
);

crypto_aead_decrypt_LOADBYTES_1_1 grp_LOADBYTES_1_1_fu_483(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LOADBYTES_1_1_fu_483_ap_start),
    .ap_done(grp_LOADBYTES_1_1_fu_483_ap_done),
    .ap_idle(grp_LOADBYTES_1_1_fu_483_ap_idle),
    .ap_ready(grp_LOADBYTES_1_1_fu_483_ap_ready),
    .p_read(npub),
    .n(32'd8),
    .ap_return(grp_LOADBYTES_1_1_fu_483_ap_return)
);

crypto_aead_decrypt_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start),
    .ap_done(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_done),
    .ap_idle(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_idle),
    .ap_ready(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_ready),
    .zext_ln224_1(npub),
    .x_out(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_x_out),
    .x_out_ap_vld(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_x_out_ap_vld)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_498(
    .ap_ready(grp_ROUND_5_6_fu_498_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_498_s_x0_read),
    .s_x1_read(grp_ROUND_5_6_fu_498_s_x1_read),
    .s_x2_read(grp_ROUND_5_6_fu_498_s_x2_read),
    .s_x3_read(grp_ROUND_5_6_fu_498_s_x3_read),
    .s_x4_read(grp_ROUND_5_6_fu_498_s_x4_read),
    .C(grp_ROUND_5_6_fu_498_C),
    .ap_return_0(grp_ROUND_5_6_fu_498_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_498_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_498_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_498_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_498_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_510(
    .ap_ready(grp_ROUND_5_6_fu_510_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_498_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_498_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_498_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_498_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_498_ap_return_4),
    .C(grp_ROUND_5_6_fu_510_C),
    .ap_return_0(grp_ROUND_5_6_fu_510_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_510_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_510_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_510_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_510_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_521(
    .ap_ready(grp_ROUND_5_6_fu_521_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_510_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_510_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_510_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_510_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_510_ap_return_4),
    .C(grp_ROUND_5_6_fu_521_C),
    .ap_return_0(grp_ROUND_5_6_fu_521_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_521_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_521_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_521_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_521_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_532(
    .ap_ready(grp_ROUND_5_6_fu_532_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_521_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_521_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_521_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_521_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_521_ap_return_4),
    .C(grp_ROUND_5_6_fu_532_C),
    .ap_return_0(grp_ROUND_5_6_fu_532_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_532_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_532_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_532_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_532_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_543(
    .ap_ready(grp_ROUND_5_6_fu_543_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_532_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_532_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_532_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_532_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_532_ap_return_4),
    .C(grp_ROUND_5_6_fu_543_C),
    .ap_return_0(grp_ROUND_5_6_fu_543_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_543_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_543_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_543_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_543_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_554(
    .ap_ready(grp_ROUND_5_6_fu_554_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_543_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_543_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_543_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_543_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_543_ap_return_4),
    .C(grp_ROUND_5_6_fu_554_C),
    .ap_return_0(grp_ROUND_5_6_fu_554_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_554_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_554_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_554_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_554_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_565(
    .ap_ready(grp_ROUND_5_6_fu_565_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_554_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_554_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_554_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_554_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_554_ap_return_4),
    .C(8'd150),
    .ap_return_0(grp_ROUND_5_6_fu_565_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_565_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_565_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_565_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_565_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_576(
    .ap_ready(grp_ROUND_5_6_fu_576_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_565_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_565_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_565_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_565_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_565_ap_return_4),
    .C(8'd135),
    .ap_return_0(grp_ROUND_5_6_fu_576_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_576_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_576_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_576_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_576_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_587(
    .ap_ready(grp_ROUND_5_6_fu_587_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_576_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_576_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_576_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_576_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_576_ap_return_4),
    .C(8'd120),
    .ap_return_0(grp_ROUND_5_6_fu_587_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_587_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_587_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_587_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_587_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_598(
    .ap_ready(grp_ROUND_5_6_fu_598_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_587_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_587_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_587_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_587_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_587_ap_return_4),
    .C(8'd105),
    .ap_return_0(grp_ROUND_5_6_fu_598_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_598_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_598_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_598_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_598_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_609(
    .ap_ready(grp_ROUND_5_6_fu_609_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_598_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_598_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_598_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_598_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_598_ap_return_4),
    .C(8'd90),
    .ap_return_0(grp_ROUND_5_6_fu_609_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_609_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_609_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_609_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_609_ap_return_4)
);

crypto_aead_decrypt_ROUND_5_6 grp_ROUND_5_6_fu_620(
    .ap_ready(grp_ROUND_5_6_fu_620_ap_ready),
    .s_x0_read(grp_ROUND_5_6_fu_609_ap_return_0),
    .s_x1_read(grp_ROUND_5_6_fu_609_ap_return_1),
    .s_x2_read(grp_ROUND_5_6_fu_609_ap_return_2),
    .s_x3_read(grp_ROUND_5_6_fu_609_ap_return_3),
    .s_x4_read(grp_ROUND_5_6_fu_609_ap_return_4),
    .C(8'd75),
    .ap_return_0(grp_ROUND_5_6_fu_620_ap_return_0),
    .ap_return_1(grp_ROUND_5_6_fu_620_ap_return_1),
    .ap_return_2(grp_ROUND_5_6_fu_620_ap_return_2),
    .ap_return_3(grp_ROUND_5_6_fu_620_ap_return_3),
    .ap_return_4(grp_ROUND_5_6_fu_620_ap_return_4)
);

crypto_aead_decrypt_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start),
    .ap_done(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_done),
    .ap_idle(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_idle),
    .ap_ready(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_ready),
    .trunc_ln230_5(trunc_ln230_reg_1836),
    .xor_ln301(xor_ln301_reg_1831),
    .m(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_m),
    .m_ap_vld(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_m_ap_vld)
);

crypto_aead_decrypt_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start),
    .ap_done(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_done),
    .ap_idle(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_idle),
    .ap_ready(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_ready),
    .x_assign_1(x_assign_1_reg_436),
    .trunc_ln230_5(trunc_ln230_reg_1836),
    .x_assign_3_out(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_x_assign_3_out),
    .x_assign_3_out_ap_vld(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_x_assign_3_out_ap_vld)
);

crypto_aead_decrypt_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start),
    .ap_done(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_done),
    .ap_idle(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_idle),
    .ap_ready(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_ready),
    .s_x3(s_x3_reg_1842),
    .t_address0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_address0),
    .t_ce0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_ce0),
    .t_we0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_we0),
    .t_d0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_d0)
);

crypto_aead_decrypt_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start),
    .ap_done(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_done),
    .ap_idle(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_idle),
    .ap_ready(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_ready),
    .s_x4_47(s_x4_75_reg_1847),
    .t_address0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_address0),
    .t_ce0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_ce0),
    .t_we0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_we0),
    .t_d0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_d0)
);

crypto_aead_decrypt_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3 grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start),
    .ap_done(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_done),
    .ap_idle(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_idle),
    .ap_ready(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_ready),
    .t_address0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_t_address0),
    .t_ce0(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_t_ce0),
    .t_q0(t_q0),
    .c_load(c),
    .result_1_out(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_result_1_out),
    .result_1_out_ap_vld(grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_result_1_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LOADBYTES_1_1_fu_475_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln248_fu_985_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln290_1_fu_1290_p2 == 1'd0) & (icmp_ln290_reg_1726 == 1'd0)) | ((1'b1 == ap_CS_fsm_state7) & ((icmp_ln290_1_fu_1290_p2 == 1'd1) | (icmp_ln290_reg_1726 == 1'd1))) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd0) & (icmp_ln273_reg_1637 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & ((icmp_ln273_1_fu_1122_p2 == 1'd1) | (icmp_ln273_reg_1637 == 1'd1))))) begin
            grp_LOADBYTES_1_1_fu_475_ap_start_reg <= 1'b1;
        end else if ((grp_LOADBYTES_1_1_fu_475_ap_ready == 1'b1)) begin
            grp_LOADBYTES_1_1_fu_475_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LOADBYTES_1_1_fu_483_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln248_fu_985_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_LOADBYTES_1_1_fu_483_ap_start_reg <= 1'b1;
        end else if ((grp_LOADBYTES_1_1_fu_483_ap_ready == 1'b1)) begin
            grp_LOADBYTES_1_1_fu_483_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln248_fu_985_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_ready == 1'b1)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln248_fu_985_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_ready == 1'b1)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_ready == 1'b1)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_ready == 1'b1)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1) & (icmp_ln230_1_reg_1814 == 1'd1))) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_ready == 1'b1)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1) & (icmp_ln230_1_reg_1814 == 1'd1))) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_ready == 1'b1)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start_reg <= 1'b1;
        end else if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_ready == 1'b1)) begin
            grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd1) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        adlen_addr_0_lcssa_reg_268 <= empty_reg_1545;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd1) & (icmp_ln273_reg_1637 == 1'd0))) begin
        adlen_addr_0_lcssa_reg_268 <= zext_ln280_fu_1139_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd0) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        adlen_assign_fu_170 <= adlen;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd0) & (icmp_ln273_reg_1637 == 1'd0))) begin
        adlen_assign_fu_170 <= add_ln277_fu_1128_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd1))) begin
        clen_addr_0_lcssa_reg_372 <= add_ln251_1_reg_1595;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln290_1_fu_1290_p2 == 1'd1) & (icmp_ln290_reg_1726 == 1'd0))) begin
        clen_addr_0_lcssa_reg_372 <= zext_ln300_fu_1296_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd0))) begin
        clen_assign_1_fu_194 <= add_ln251_reg_1589;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        clen_assign_1_fu_194 <= add_ln297_fu_1360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1))) begin
        i_reg_382 <= 4'd0;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        i_reg_382 <= add_ln230_fu_1322_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln248_fu_985_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        retval_0_reg_457 <= 1'd1;
    end else if (((icmp_ln248_reg_1560 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        retval_0_reg_457 <= result_fu_1493_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd1) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x0_1716_reg_314 <= grp_ROUND_5_6_fu_620_ap_return_0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd1) & (icmp_ln273_reg_1637 == 1'd0))) begin
        s_x0_1716_reg_314 <= s_x0_27_fu_174;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln271_fu_1045_p2 == 1'd1))) begin
        s_x0_2717_reg_362 <= grp_ROUND_5_6_fu_620_ap_return_0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln271_reg_1633 == 1'd0))) begin
        s_x0_2717_reg_362 <= grp_ROUND_5_6_fu_554_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd0) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x0_27_fu_174 <= grp_ROUND_5_6_fu_620_ap_return_0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1))) begin
        s_x0_27_fu_174 <= grp_ROUND_5_6_fu_554_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd0))) begin
        s_x0_3_fu_198 <= ap_phi_mux_s_x0_2717_phi_fu_365_p4;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        s_x0_3_fu_198 <= grp_ROUND_5_6_fu_554_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd0) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x1_15_fu_178 <= grp_ROUND_5_6_fu_620_ap_return_1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1))) begin
        s_x1_15_fu_178 <= grp_ROUND_5_6_fu_554_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd1) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x1_1_reg_305 <= grp_ROUND_5_6_fu_620_ap_return_1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd1) & (icmp_ln273_reg_1637 == 1'd0))) begin
        s_x1_1_reg_305 <= s_x1_15_fu_178;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln271_fu_1045_p2 == 1'd1))) begin
        s_x1_2719_reg_352 <= grp_ROUND_5_6_fu_620_ap_return_1;
    end else if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln271_reg_1633 == 1'd0))) begin
        s_x1_2719_reg_352 <= grp_ROUND_5_6_fu_554_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd0))) begin
        s_x1_3_fu_202 <= ap_phi_mux_s_x1_2719_phi_fu_355_p4;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        s_x1_3_fu_202 <= grp_ROUND_5_6_fu_554_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd1))) begin
        s_x1_4_reg_425 <= ap_phi_mux_s_x1_2719_phi_fu_355_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln290_1_fu_1290_p2 == 1'd1) & (icmp_ln290_reg_1726 == 1'd0))) begin
        s_x1_4_reg_425 <= s_x1_3_fu_202;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd1) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x2_1_reg_296 <= grp_ROUND_5_6_fu_620_ap_return_2;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd1) & (icmp_ln273_reg_1637 == 1'd0))) begin
        s_x2_1_reg_296 <= s_x2_46_fu_182;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln271_fu_1045_p2 == 1'd1))) begin
        s_x2_2720_reg_342 <= grp_ROUND_5_6_fu_620_ap_return_2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln271_reg_1633 == 1'd0))) begin
        s_x2_2720_reg_342 <= grp_ROUND_5_6_fu_554_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd0))) begin
        s_x2_3_fu_206 <= ap_phi_mux_s_x2_2720_phi_fu_345_p4;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        s_x2_3_fu_206 <= grp_ROUND_5_6_fu_554_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd0) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x2_46_fu_182 <= grp_ROUND_5_6_fu_620_ap_return_2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1))) begin
        s_x2_46_fu_182 <= grp_ROUND_5_6_fu_554_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd1))) begin
        s_x2_4_reg_414 <= ap_phi_mux_s_x2_2720_phi_fu_345_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln290_1_fu_1290_p2 == 1'd1) & (icmp_ln290_reg_1726 == 1'd0))) begin
        s_x2_4_reg_414 <= s_x2_3_fu_206;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd0) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x3_16_fu_186 <= s_x3_15_fu_1034_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1))) begin
        s_x3_16_fu_186 <= grp_ROUND_5_6_fu_554_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd1) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x3_1_reg_287 <= s_x3_15_fu_1034_p2;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd1) & (icmp_ln273_reg_1637 == 1'd0))) begin
        s_x3_1_reg_287 <= s_x3_16_fu_186;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln271_fu_1045_p2 == 1'd1))) begin
        s_x3_2721_reg_332 <= s_x3_15_fu_1034_p2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln271_reg_1633 == 1'd0))) begin
        s_x3_2721_reg_332 <= grp_ROUND_5_6_fu_554_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd0))) begin
        s_x3_3_fu_210 <= ap_phi_mux_s_x3_2721_phi_fu_335_p4;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        s_x3_3_fu_210 <= grp_ROUND_5_6_fu_554_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd1))) begin
        s_x3_4722_reg_403 <= ap_phi_mux_s_x3_2721_phi_fu_335_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln290_1_fu_1290_p2 == 1'd1) & (icmp_ln290_reg_1726 == 1'd0))) begin
        s_x3_4722_reg_403 <= s_x3_3_fu_210;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd1) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x4_1_reg_278 <= s_x4_15_fu_1040_p2;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd1) & (icmp_ln273_reg_1637 == 1'd0))) begin
        s_x4_1_reg_278 <= s_x4_48_fu_190;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln271_fu_1045_p2 == 1'd1))) begin
        s_x4_2723_reg_323 <= s_x4_15_fu_1040_p2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln271_reg_1633 == 1'd0))) begin
        s_x4_2723_reg_323 <= grp_ROUND_5_6_fu_554_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln273_fu_1059_p2 == 1'd0) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        s_x4_48_fu_190 <= s_x4_15_fu_1040_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1))) begin
        s_x4_48_fu_190 <= grp_ROUND_5_6_fu_554_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd1))) begin
        s_x4_4_reg_393 <= s_x4_61_fu_1212_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln290_1_fu_1290_p2 == 1'd1) & (icmp_ln290_reg_1726 == 1'd0))) begin
        s_x4_4_reg_393 <= s_x4_62_fu_214;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd0))) begin
        s_x4_62_fu_214 <= s_x4_61_fu_1212_p2;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        s_x4_62_fu_214 <= grp_ROUND_5_6_fu_554_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1) & (icmp_ln230_1_reg_1814 == 1'd0))) begin
        x_addr_0_lcssa_i_reg_447 <= x_assign_1_reg_436;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln230_1_reg_1814 == 1'd1))) begin
        x_addr_0_lcssa_i_reg_447 <= grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_x_assign_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done) & (icmp_ln290_fu_1227_p2 == 1'd1))) begin
        x_assign_1_reg_436 <= ap_phi_mux_s_x0_2717_phi_fu_365_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln290_1_fu_1290_p2 == 1'd1) & (icmp_ln290_reg_1726 == 1'd0))) begin
        x_assign_1_reg_436 <= s_x0_3_fu_198;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K1_reg_1576 <= grp_LOADBYTES_1_1_fu_475_ap_return;
        N1_reg_1584 <= grp_LOADBYTES_1_1_fu_483_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln251_1_reg_1595 <= add_ln251_1_fu_1000_p2;
        add_ln251_reg_1589 <= add_ln251_fu_994_p2;
        icmp_ln271_reg_1633 <= icmp_ln271_fu_1045_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_16_reg_1550 <= empty_16_fu_967_p1;
        empty_17_reg_1555 <= empty_17_fu_971_p1;
        empty_reg_1545 <= empty_fu_963_p1;
        icmp_ln248_reg_1560 <= icmp_ln248_fu_985_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & ((icmp_ln290_1_fu_1290_p2 == 1'd1) | (icmp_ln290_reg_1726 == 1'd1)))) begin
        icmp_ln230_1_reg_1814 <= icmp_ln230_1_fu_1305_p2;
        trunc_ln300_reg_1809 <= trunc_ln300_fu_1300_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
        icmp_ln273_reg_1637 <= icmp_ln273_fu_1059_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln290_reg_1726 <= icmp_ln290_fu_1227_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        reg_958 <= grp_LOADBYTES_1_1_fu_475_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_result_1_out_ap_vld == 1'b1))) begin
        result_1_loc_fu_150 <= grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_result_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_x3_reg_1842 <= s_x3_fu_1465_p2;
        s_x4_75_reg_1847 <= s_x4_75_fu_1471_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln230_1_reg_1814 == 1'd1))) begin
        trunc_ln230_reg_1836 <= trunc_ln230_fu_1402_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln273_1_fu_1122_p2 == 1'd1) | (icmp_ln273_reg_1637 == 1'd1)))) begin
        trunc_ln280_reg_1716 <= trunc_ln280_fu_1143_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        xor_ln292_reg_1818 <= xor_ln292_fu_1311_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        xor_ln301_reg_1831 <= xor_ln301_fu_1395_p2;
    end
end

always @ (*) begin
    if ((grp_LOADBYTES_1_1_fu_475_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state11_on_subcall_done)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_LOADBYTES_1_1_fu_475_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_LOADBYTES_1_1_fu_475_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln273_1_fu_1122_p2 == 1'd1) & (icmp_ln273_reg_1637 == 1'd0))) begin
        ap_phi_mux_adlen_addr_0_lcssa_phi_fu_271_p4 = zext_ln280_fu_1139_p1;
    end else begin
        ap_phi_mux_adlen_addr_0_lcssa_phi_fu_271_p4 = adlen_addr_0_lcssa_reg_268;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln290_1_fu_1290_p2 == 1'd1) & (icmp_ln290_reg_1726 == 1'd0))) begin
        ap_phi_mux_clen_addr_0_lcssa_phi_fu_375_p4 = zext_ln300_fu_1296_p1;
    end else begin
        ap_phi_mux_clen_addr_0_lcssa_phi_fu_375_p4 = clen_addr_0_lcssa_reg_372;
    end
end

always @ (*) begin
    if (((icmp_ln248_reg_1560 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_phi_mux_retval_0_phi_fu_461_p4 = result_fu_1493_p2;
    end else begin
        ap_phi_mux_retval_0_phi_fu_461_p4 = retval_0_reg_457;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        ap_phi_mux_s_x0_2717_phi_fu_365_p4 = grp_ROUND_5_6_fu_554_ap_return_0;
    end else begin
        ap_phi_mux_s_x0_2717_phi_fu_365_p4 = s_x0_2717_reg_362;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        ap_phi_mux_s_x1_2719_phi_fu_355_p4 = grp_ROUND_5_6_fu_554_ap_return_1;
    end else begin
        ap_phi_mux_s_x1_2719_phi_fu_355_p4 = s_x1_2719_reg_352;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        ap_phi_mux_s_x2_2720_phi_fu_345_p4 = grp_ROUND_5_6_fu_554_ap_return_2;
    end else begin
        ap_phi_mux_s_x2_2720_phi_fu_345_p4 = s_x2_2720_reg_342;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        ap_phi_mux_s_x3_2721_phi_fu_335_p4 = grp_ROUND_5_6_fu_554_ap_return_3;
    end else begin
        ap_phi_mux_s_x3_2721_phi_fu_335_p4 = s_x3_2721_reg_332;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        ap_phi_mux_s_x4_2723_phi_fu_326_p4 = grp_ROUND_5_6_fu_554_ap_return_4;
    end else begin
        ap_phi_mux_s_x4_2723_phi_fu_326_p4 = s_x4_2723_reg_323;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln230_1_reg_1814 == 1'd1))) begin
        ap_phi_mux_x_addr_0_lcssa_i_phi_fu_450_p4 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_x_assign_3_out;
    end else begin
        ap_phi_mux_x_addr_0_lcssa_i_phi_fu_450_p4 = x_addr_0_lcssa_i_reg_447;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_LOADBYTES_1_1_fu_475_n = trunc_ln300_reg_1809;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        grp_LOADBYTES_1_1_fu_475_n = trunc_ln280_reg_1716;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_LOADBYTES_1_1_fu_475_n = 32'd8;
    end else begin
        grp_LOADBYTES_1_1_fu_475_n = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_LOADBYTES_1_1_fu_475_p_read = c;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0)))) begin
        grp_LOADBYTES_1_1_fu_475_p_read = ad;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_LOADBYTES_1_1_fu_475_p_read = k;
    end else begin
        grp_LOADBYTES_1_1_fu_475_p_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0)))) begin
        grp_ROUND_5_6_fu_498_C = 8'd150;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_ROUND_5_6_fu_498_C = 8'd240;
    end else begin
        grp_ROUND_5_6_fu_498_C = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_ROUND_5_6_fu_498_s_x0_read = s_x0_60_fu_1438_p2;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        grp_ROUND_5_6_fu_498_s_x0_read = reg_958;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        grp_ROUND_5_6_fu_498_s_x0_read = s_x0_53_fu_1205_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_5_6_fu_498_s_x0_read = s_x0_46_fu_1148_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_5_6_fu_498_s_x0_read = 64'd9241399655273594880;
    end else begin
        grp_ROUND_5_6_fu_498_s_x0_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_ROUND_5_6_fu_498_s_x1_read = s_x1_34_fu_1445_p2;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        grp_ROUND_5_6_fu_498_s_x1_read = s_x1_3_fu_202;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        grp_ROUND_5_6_fu_498_s_x1_read = s_x1_1_reg_305;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_5_6_fu_498_s_x1_read = s_x1_15_fu_178;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_5_6_fu_498_s_x1_read = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_x_4_out;
    end else begin
        grp_ROUND_5_6_fu_498_s_x1_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_ROUND_5_6_fu_498_s_x2_read = s_x2_59_fu_1451_p2;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        grp_ROUND_5_6_fu_498_s_x2_read = s_x2_3_fu_206;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        grp_ROUND_5_6_fu_498_s_x2_read = s_x2_1_reg_296;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_5_6_fu_498_s_x2_read = s_x2_46_fu_182;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_5_6_fu_498_s_x2_read = K1_reg_1576;
    end else begin
        grp_ROUND_5_6_fu_498_s_x2_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_ROUND_5_6_fu_498_s_x3_read = s_x3_4722_reg_403;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        grp_ROUND_5_6_fu_498_s_x3_read = s_x3_3_fu_210;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        grp_ROUND_5_6_fu_498_s_x3_read = s_x3_1_reg_287;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_5_6_fu_498_s_x3_read = s_x3_16_fu_186;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_5_6_fu_498_s_x3_read = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_x_out;
    end else begin
        grp_ROUND_5_6_fu_498_s_x3_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_ROUND_5_6_fu_498_s_x4_read = s_x4_4_reg_393;
    end else if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        grp_ROUND_5_6_fu_498_s_x4_read = s_x4_62_fu_214;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0))) begin
        grp_ROUND_5_6_fu_498_s_x4_read = s_x4_1_reg_278;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_ROUND_5_6_fu_498_s_x4_read = s_x4_48_fu_190;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_ROUND_5_6_fu_498_s_x4_read = N1_reg_1584;
    end else begin
        grp_ROUND_5_6_fu_498_s_x4_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0)))) begin
        grp_ROUND_5_6_fu_510_C = 8'd135;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_ROUND_5_6_fu_510_C = 8'd225;
    end else begin
        grp_ROUND_5_6_fu_510_C = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0)))) begin
        grp_ROUND_5_6_fu_521_C = 8'd120;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_ROUND_5_6_fu_521_C = 8'd210;
    end else begin
        grp_ROUND_5_6_fu_521_C = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0)))) begin
        grp_ROUND_5_6_fu_532_C = 8'd105;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_ROUND_5_6_fu_532_C = 8'd195;
    end else begin
        grp_ROUND_5_6_fu_532_C = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0)))) begin
        grp_ROUND_5_6_fu_543_C = 8'd90;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_ROUND_5_6_fu_543_C = 8'd180;
    end else begin
        grp_ROUND_5_6_fu_543_C = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln271_reg_1633 == 1'd0)))) begin
        grp_ROUND_5_6_fu_554_C = 8'd75;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_ROUND_5_6_fu_554_C = 8'd165;
    end else begin
        grp_ROUND_5_6_fu_554_C = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln230_fu_1316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        m = trunc_ln230_5_fu_1355_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) & (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_m_ap_vld == 1'b1))) begin
        m = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_m;
    end else begin
        m = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln230_fu_1316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        m_ap_vld = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        m_ap_vld = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_m_ap_vld;
    end else begin
        m_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mlen_ap_vld = 1'b1;
    end else begin
        mlen_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        t_address0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_t_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        t_address0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        t_address0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_address0;
    end else begin
        t_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        t_ce0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_t_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        t_ce0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        t_ce0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_ce0;
    end else begin
        t_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        t_d0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_d0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        t_d0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_d0;
    end else begin
        t_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        t_we0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_t_we0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        t_we0 = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_t_we0;
    end else begin
        t_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln248_fu_985_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((icmp_ln248_fu_985_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln271_fu_1045_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln273_1_fu_1122_p2 == 1'd1) | (icmp_ln273_reg_1637 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & ((icmp_ln290_1_fu_1290_p2 == 1'd1) | (icmp_ln290_reg_1726 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln230_fu_1316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1) & (icmp_ln230_1_reg_1814 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((1'b1 == ap_CS_fsm_state10) & (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b1) & (icmp_ln230_1_reg_1814 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (1'b0 == ap_block_state11_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln230_fu_1322_p2 = (i_reg_382 + 4'd1);

assign add_ln251_1_fu_1000_p2 = ($signed(trunc_ln251_fu_991_p1) + $signed(61'd2305843009213693936));

assign add_ln251_fu_994_p2 = ($signed(clen) + $signed(64'd18446744073709551600));

assign add_ln277_fu_1128_p2 = ($signed(adlen_assign_fu_170) + $signed(64'd18446744073709551608));

assign add_ln297_fu_1360_p2 = ($signed(clen_assign_1_fu_194) + $signed(64'd18446744073709551608));

assign add_ln324_fu_1479_p2 = ($signed(result_1_loc_fu_150) + $signed(9'd511));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11_on_subcall_done = ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_done == 1'b0) | (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_done == 1'b0) | (grp_LOADBYTES_1_1_fu_483_ap_done == 1'b0) | (grp_LOADBYTES_1_1_fu_475_ap_done == 1'b0) | (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_LOADBYTES_1_1_fu_475_ap_done == 1'b0) & (icmp_ln271_reg_1633 == 1'd0));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign ap_return = ((ap_phi_mux_retval_0_phi_fu_461_p4[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign empty_16_fu_967_p1 = adlen[2:0];

assign empty_17_fu_971_p1 = clen[2:0];

assign empty_fu_963_p1 = adlen[60:0];

assign grp_LOADBYTES_1_1_fu_475_ap_start = grp_LOADBYTES_1_1_fu_475_ap_start_reg;

assign grp_LOADBYTES_1_1_fu_483_ap_start = grp_LOADBYTES_1_1_fu_483_ap_start_reg;

assign grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_11_fu_491_ap_start_reg;

assign grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_ap_start_reg;

assign grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_12_fu_659_ap_start_reg;

assign grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_13_fu_665_ap_start_reg;

assign grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_230_1_fu_643_ap_start_reg;

assign grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_235_1_fu_651_ap_start_reg;

assign grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start = grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_323_3_fu_671_ap_start_reg;

assign icmp_ln230_1_fu_1305_p2 = (($signed(trunc_ln300_fu_1300_p1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_1316_p2 = ((i_reg_382 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln248_fu_985_p2 = ((tmp_2_fu_975_p4 == 60'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_1045_p2 = ((adlen == 64'd0) ? 1'b1 : 1'b0);

assign icmp_ln273_1_fu_1122_p2 = ((tmp_4_fu_1112_p4 == 61'd0) ? 1'b1 : 1'b0);

assign icmp_ln273_fu_1059_p2 = ((tmp_3_fu_1050_p4 == 61'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_1_fu_1290_p2 = ((tmp_6_fu_1280_p4 == 61'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_1227_p2 = ((tmp_5_fu_1218_p4 == 61'd0) ? 1'b1 : 1'b0);

assign lshr_ln230_fu_1350_p2 = xor_ln292_reg_1818 >> zext_ln230_fu_1346_p1;

assign mlen = ($signed(clen) + $signed(64'd18446744073709551600));

assign or_ln303_fu_1412_p2 = (reg_958 | ap_phi_mux_x_addr_0_lcssa_i_phi_fu_450_p4);

assign result_fu_1493_p2 = (tmp_7_fu_1485_p3 ^ 1'd1);

assign s_x0_46_fu_1148_p2 = (s_x0_27_fu_174 ^ grp_LOADBYTES_1_1_fu_475_ap_return);

assign s_x0_53_fu_1205_p2 = (xor_ln281_fu_1199_p2 ^ s_x0_1716_reg_314);

assign s_x0_60_fu_1438_p2 = (shl_ln304_fu_1432_p2 ^ or_ln303_fu_1412_p2);

assign s_x1_34_fu_1445_p2 = (s_x1_4_reg_425 ^ grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_x_4_out);

assign s_x2_59_fu_1451_p2 = (s_x2_4_reg_414 ^ K1_reg_1576);

assign s_x3_15_fu_1034_p2 = (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_x_4_out ^ grp_ROUND_5_6_fu_620_ap_return_3);

assign s_x3_fu_1465_p2 = (grp_crypto_aead_decrypt_Pipeline_VITIS_LOOP_224_1_fu_468_x_4_out ^ grp_ROUND_5_6_fu_620_ap_return_3);

assign s_x4_15_fu_1040_p2 = (grp_ROUND_5_6_fu_620_ap_return_4 ^ K1_reg_1576);

assign s_x4_61_fu_1212_p2 = (ap_phi_mux_s_x4_2723_phi_fu_326_p4 ^ 64'd1);

assign s_x4_75_fu_1471_p2 = (grp_ROUND_5_6_fu_620_ap_return_4 ^ K1_reg_1576);

assign shl_ln1_fu_1179_p3 = {{adlen_addr_0_lcssa_reg_268}, {3'd0}};

assign shl_ln281_fu_1193_p2 = 64'd128 << sub_ln281_fu_1187_p2;

assign shl_ln2_fu_1332_p3 = {{trunc_ln230_4_fu_1328_p1}, {3'd0}};

assign shl_ln304_fu_1432_p2 = 64'd128 << sub_ln304_fu_1426_p2;

assign shl_ln4_fu_1418_p3 = {{clen_addr_0_lcssa_reg_372}, {3'd0}};

assign sub_ln230_fu_1340_p2 = ($signed(6'd56) - $signed(shl_ln2_fu_1332_p3));

assign sub_ln281_fu_1187_p2 = (64'd56 - shl_ln1_fu_1179_p3);

assign sub_ln304_fu_1426_p2 = (64'd56 - shl_ln4_fu_1418_p3);

assign tmp_2_fu_975_p4 = {{clen[63:4]}};

assign tmp_3_fu_1050_p4 = {{adlen[63:3]}};

assign tmp_4_fu_1112_p4 = {{adlen_assign_fu_170[63:3]}};

assign tmp_5_fu_1218_p4 = {{add_ln251_reg_1589[63:3]}};

assign tmp_6_fu_1280_p4 = {{clen_assign_1_fu_194[63:3]}};

assign tmp_7_fu_1485_p3 = add_ln324_fu_1479_p2[32'd8];

assign trunc_ln230_4_fu_1328_p1 = i_reg_382[2:0];

assign trunc_ln230_5_fu_1355_p1 = lshr_ln230_fu_1350_p2[7:0];

assign trunc_ln230_fu_1402_p1 = clen_addr_0_lcssa_reg_372[30:0];

assign trunc_ln251_fu_991_p1 = clen[60:0];

assign trunc_ln280_fu_1143_p1 = ap_phi_mux_adlen_addr_0_lcssa_phi_fu_271_p4[31:0];

assign trunc_ln300_fu_1300_p1 = ap_phi_mux_clen_addr_0_lcssa_phi_fu_375_p4[31:0];

assign xor_ln281_fu_1199_p2 = (shl_ln281_fu_1193_p2 ^ grp_LOADBYTES_1_1_fu_475_ap_return);

assign xor_ln292_fu_1311_p2 = (s_x0_3_fu_198 ^ grp_LOADBYTES_1_1_fu_475_ap_return);

assign xor_ln301_fu_1395_p2 = (x_assign_1_reg_436 ^ grp_LOADBYTES_1_1_fu_475_ap_return);

assign zext_ln230_fu_1346_p1 = sub_ln230_fu_1340_p2;

assign zext_ln280_fu_1139_p1 = empty_16_reg_1550;

assign zext_ln300_fu_1296_p1 = empty_17_reg_1555;

endmodule //crypto_aead_decrypt
