// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module crypto_aead_encrypt_ROR_r (
        ap_ready,
        x,
        n,
        ap_return
);


output   ap_ready;
input  [63:0] x;
input  [5:0] n;
output  [63:0] ap_return;

wire   [63:0] zext_ln8_fu_22_p1;
wire   [5:0] sub_ln8_fu_32_p2;
wire   [63:0] zext_ln8_1_fu_38_p1;
wire   [63:0] shl_ln8_fu_42_p2;
wire   [63:0] lshr_ln8_fu_26_p2;

assign ap_ready = 1'b1;

assign ap_return = (shl_ln8_fu_42_p2 | lshr_ln8_fu_26_p2);

assign lshr_ln8_fu_26_p2 = x >> zext_ln8_fu_22_p1;

assign shl_ln8_fu_42_p2 = x << zext_ln8_1_fu_38_p1;

assign sub_ln8_fu_32_p2 = (6'd0 - n);

assign zext_ln8_1_fu_38_p1 = sub_ln8_fu_32_p2;

assign zext_ln8_fu_22_p1 = n;

endmodule //crypto_aead_encrypt_ROR_r
